In [1]:
import pandas as pd
import numpy as np

In [2]:
#Clean CSVs for human and automatic eval
raw_human = pd.read_csv('human_eval_bin.csv')
raw_auto = pd.read_csv('auto_eval_toy.csv')
raw_auto['fkre.GEN']
raw_human

,axis,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,coherence,0,0,0,0,3.666667,4.333333,4,3.0,4.0,3.333333,4,0,2,0,0,0
1,ease,0,0,0,0,2.333333,4.666667,4,3.5,4.5,3.666667,5,0,2,0,0,0
2,org,0,0,0,0,3.000000,4.333333,4,2.0,4.5,2.666667,4,0,1,0,0,0

In [88]:
human_df = raw_human.T
header_df = human_df.iloc[0]
human_df.columns = header_df
human_df = human_df[1:]
human_clean = human_df[(human_df != 0).all(axis=1)]
human_clean.index = [int(i) for i in human_clean.index]
human_clean["average_rank"] = human_clean.mean(axis=1)

/var/folders/st/p2js96993zq5v79qwdjfx64m0000gn/T/ipykernel_23683/1777346292.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  human_clean["average_rank"] = human_clean.mean(axis=1)

In [89]:
human_clean["fkre"] = raw_auto.loc[human_clean.index, ["fkre.GEN"]]
human_clean["fkgl"] = raw_auto.loc[human_clean.index, ["fkgl.GEN"]]
# set FKGL to negative so it's the same direction as FKRE

/var/folders/st/p2js96993zq5v79qwdjfx64m0000gn/T/ipykernel_23683/3267492828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  human_clean["fkre"] = raw_auto.loc[human_clean.index, ["fkre.GEN"]]
/var/folders/st/p2js96993zq5v79qwdjfx64m0000gn/T/ipykernel_23683/3267492828.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  human_clean["fkgl"] = raw_auto.loc[human_clean.index, ["fkgl.GEN"]]

In [77]:
human_clean.loc[human_clean.average_rank < 4]

axis coherence      ease       org average_rank    fkre    fkgl
4     3.666667  2.333333       3.0          3.0   2.822  26.206
7          3.0       3.5       2.0     2.833333  22.650  23.134
9     3.333333  3.666667  2.666667     3.222222   9.552  24.659
12           2         2         1     1.666667 -11.133  28.103

In [78]:
human_clean.loc[human_clean.average_rank > 4]

axis coherence      ease       org average_rank    fkre    fkgl
5     4.333333  4.666667  4.333333     4.444444 -38.575  41.992
8          4.0       4.5       4.5     4.333333  22.685  19.074
10           4         5         4     4.333333  17.414  21.739

In [81]:
good = human_clean.loc[human_clean.average_rank > 4].fkgl.mean()
bad = human_clean.loc[human_clean.average_rank < 4].fkgl.mean()

In [83]:
human_clean = human_clean

In [94]:
temp = human_clean.loc[human_clean.fkre > 0] # drop extreme FKRE rows
temp.fkgl = - temp.fkgl # set FKGL to negative to flip the sign on correlation
temp = temp.sample(n=12, replace=True, random_state=1234)

correlation, pval = spearmanr(temp.average_rank, temp.fkgl)
print("FKGL")
print(f"Correlation: {correlation:.5f}, p-value: {pval:.5f}")

correlation, pval = spearmanr(temp.average_rank, temp.fkre)
print("FKRE")
print(f"Correlation: {correlation:.5f}, p-value: {pval:.5f}")

FKGL
Correlation: 0.81634, p-value: 0.00120
FKRE
Correlation: 0.60854, p-value: 0.03575

/var/folders/st/p2js96993zq5v79qwdjfx64m0000gn/T/ipykernel_23683/143100019.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.fkgl = - temp.fkgl # set FKGL to negative to flip the sign on correlation